### PR TITLE
Fix #7 + fix minimum/maximum date on Android + add some functions

### LINKED ISSUE #7: How to get selected date?
Hi there, cool plugin ! .I just wondering why cannot get the date from method dateSelected. 
this is the result i get 
{"eventName":"dateSelected","object":{},"data":{"date":{},"selected":true}}

### PR DESCRIPTION
**Pull request by mickaeleuranie**
- Get same date format from both Android and iOS platforms
- Fix error if no minimum or maximum date is set for Android
- Programmatically (de)select date and get date (`selectDate()`, `deselecteDate()`, `getDate()`)

### CODE REVIEW

**Comment by rhanb** [comment]
Seems good! I'll merge it once I'll have test it on Android and iOS. 
Juste one small question: why did you had `private _date;` on the both classes even if you never give it a value?

**Comment by mickaeleuranie** [comment]
@rhanb Thanks ! You're right, I'm setting it in iOS (function `pageChanged()`) and in all three new functions but I forgot to add `this._date = date;` in Android file. I'm using this value for `getDate()` function. I'll update this right now!

**Comment by rhanb** [comment]
maybe change the name to a more explicit one. Since you changed the value when the page changes, I guess the date corresponds to the week/month page, right? So maybe change the name to: `currentPageDate`. And the function to: `getCurrentPageDate`

**Comment by mickaeleuranie** [comment]
At first it was only for the `getDate()` function, to get programmatically selected date, but I didn't think about agenda selection mode : it was ok for `single` mode but not `multiple` so I removed this function and all `_date` variables for now. I'll add a `getSelectedDates()` function in the future, returning an array of every selected dates.

**Comment by rhanb** [comment]
ok ça marche, merci @mickaeleuranie pour ta contribution! je teste ça demain, je merge, je t'ajoute en contributeur et je publie une nouvelle version 😄

**Pull request merged**
